### PR TITLE
Add params.unpack functionality to ./in

### PR DESCRIPTION
**Pull request by aemengo**
This PR attempts to bring the project to feature parity with the concourse/s3 resource. With respect to the ability to uncompress archives retrieved from a remote  blobstore via the `params: { unpack: true }` flag.

https://github.com/concourse/s3-resource#parameters

### CODE REVIEW

**Comment by frodenas** [comment]
Thanks @aemengo. All the unit and integration tests are passing, awesome work!

Can you please run `make format` to fix some indentations before I merge it?

**Comment by frodenas** [comment]
Thanks @aemengo!

**Comment by marcelmojzis** [comment]
Hello @frodenas, the latest build seems to fail with the following error:

```
error running command: rename /tmp/gcsresource-931770045 /tmp/build/get/file.json: invalid cross-device link
```

Could it be related to this PR? Thx

**Comment by frodenas** [comment]
@marcelmojzis Yes, the issue is related to this PR.

@aemengo I've reverted this change. The problem lies at the [DownloadFile](https://github.com/aemengo/gcs-resource/blob/add-unpack-to-in/gcsclient.go#L94) function. It is now using [os.TempDir()](https://github.com/aemengo/gcs-resource/blob/add-unpack-to-in/gcsclient.go#L114) to download the file from GCS to a `tmp` directory. If the `tmp` and the final location does not belong to the same filesystem, the `rename` function will return the `invalid cross-device link` error.

**Comment by frodenas** [comment]
@aemengo BTW, the S3 resource seems to [preserve the original tarball](https://github.com/concourse/s3-resource/blob/master/in/command.go#L88), we should be doing the same here.

**Comment by aemengo** [comment]
@frodenas Very sorry about that. If we wrote the temp file to the destinationDir in that method, would you approve of that?

```
...

localFile, err := ioutil.TempFile(destinationDir, "gcsresource-")
if err != nil {
	return "", err
}
```

**Comment by frodenas** [comment]
@aemengo no problem, can we please mimic the `s3-resource` logic? We download the file to the target location (as it is today), and if the `unpack` flag is set, untar it.

**Comment by aemengo** [comment]
@frodenas fair enough.

**Pull request merged**
