### PR TITLE
using tar/unzip util to handle archive instead of golang lib

### PR DESCRIPTION
**Pull request by fredwangwang**
The original implementation does not handle symlink & hardlink, make the inflated file corrupted.
Using native tar/unzip utility for the best result without the trouble to implement a full-featured archiver.

Specific command copied directly from [concourse/s3-resource](https://github.com/concourse/s3-resource/blob/master/in/archive.go#L60-L69)

Note: before I copied the command from S3-resource, I also tried https://github.com/mholt/archiver as a replacement. But turns out it only works partially. The file I tested with is a Docker container archive, which is a rather complicated target. `mholt/archiver` was not able to handle some of the contents (links, especially, seems like links redirect several times is a nightmare to handle) in the archive. So I went with tar & unzip utilities, works perfectly. (Why Reinvent the wheel when there is a perfect one last decades? 😄)

### CODE REVIEW

**Comment by fredwangwang** [comment]
This pr solves #18 #16

**Comment by frodenas** [comment]
Thanks @fredwangwang

**Comment by frodenas** [comment]
@fredwangwang FYI, after merging this PR, I realized the integration tests were failing (see [Job #33.2](https://travis-ci.org/frodenas/gcs-resource/jobs/475396305#L490)), because the archive files were deleted after uncompressing them.

I've restored the previous gunzip logic (https://github.com/frodenas/gcs-resource/commit/15238531457ac19305b125990763cf337cb87d7e) in order to preserve the original file (`gunzip` does not preserve the file name) and also removed the `os.Remove` calls (https://github.com/frodenas/gcs-resource/commit/b518cc22143bc9924482e9e25f4e57849379a9de). This should not affect the symlink & hardlink, as it's still using untar/unzip.

**Comment by fredwangwang** [comment]
Thats alright. The removal of the original file is copied directly from s3
resource. Thanks for the info

**Pull request merged**
